CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, uuid TEXT UNIQUE NOT NULL,
 sub_token TEXT UNIQUE NOT NULL, note TEXT DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1,
 quota_bytes INTEGER NOT NULL DEFAULT 0, used_bytes INTEGER NOT NULL DEFAULT 0, expire_at INTEGER NOT NULL DEFAULT 0,
 device_limit INTEGER NOT NULL DEFAULT 1, transport TEXT NOT NULL DEFAULT 'both', obfuscate INTEGER NOT NULL DEFAULT 0,
 created_at INTEGER NOT NULL, updated_at INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS clean_ips (id INTEGER PRIMARY KEY AUTOINCREMENT, address TEXT UNIQUE NOT NULL, remark TEXT DEFAULT '', country TEXT DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1, added_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS user_ips (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, ip TEXT NOT NULL, proto TEXT NOT NULL DEFAULT 'ws', first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL, hits INTEGER NOT NULL DEFAULT 1, UNIQUE(user_id,ip));
CREATE TABLE IF NOT EXISTS traffic_log (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, ts INTEGER NOT NULL, up INTEGER NOT NULL DEFAULT 0, down INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER NOT NULL, event TEXT, ip TEXT, detail TEXT);
CREATE TABLE IF NOT EXISTS proxies (
 id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, host TEXT NOT NULL, port INTEGER NOT NULL,
 username TEXT DEFAULT '', password TEXT DEFAULT '', remark TEXT DEFAULT '', country TEXT DEFAULT '',
 country_name TEXT DEFAULT '', city TEXT DEFAULT '', isp TEXT DEFAULT '', exit_ip TEXT DEFAULT '',
 healthy INTEGER DEFAULT 0, latency_ms INTEGER DEFAULT 0, last_error TEXT DEFAULT '', checked_at INTEGER DEFAULT 0,
 enabled INTEGER NOT NULL DEFAULT 1, added_at INTEGER NOT NULL, UNIQUE(kind,host,port,username));
CREATE INDEX IF NOT EXISTS idx_ips_user ON user_ips(user_id,last_seen);
CREATE INDEX IF NOT EXISTS idx_traf_user ON traffic_log(user_id,ts);
CREATE INDEX IF NOT EXISTS idx_proxies_enabled ON proxies(enabled);
